baseURL = "/"
languageCode = "en-gb"
title = "The Bagnall Centre"

disableKinds = ["RSS"]
enableRobotsTXT = true
disableAliases = true

[mediaTypes]
    [mediaTypes."application/prs.factopolis-algolia"]
    suffix = "algolia.json"

[outputFormats.Algolia]
    mediaType = "application/prs.factopolis-algolia"
    isPlainText = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS", "Algolia"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[taxonomies]
treatment = "treatments"
category = "categories"
event_category = "event_categories"

[[menu.main]]
    name = "Therapy & Wellbeing"
    weight = 20
    url = "/treatments/therapies/"

[[menu.main]]
    name = "Nutrition & Lifestyle"
    weight = 30
    url = "/treatments/nutrition/"

[[menu.main]]
    name = "News"
    weight = 50
    url = "/news/"
    identifier = "news"


[[menu.nutrition]]
    name = "Nutrition"
    url = "/treatments/nutrition/"
    weight = 10

[[menu.nutrition]]
    name = "Lifestyle"
    url = "/treatments/lifestyle/"
    weight = 20


[[menu.therapies]]
    name = "Therapies"
    url = "/treatments/therapies/"
    weight = 10

[[menu.therapies]]
    name = "Wellbeing"
    url = "/treatments/wellbeing/"
    weight = 20