[build]
    command = "npm run build && bash algolia-push.sh"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.34"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "npm run build:preview"

    