backend:
  name: git-gateway
  
media_folder: "content/uploads"
public_folder: "/uploads"
collections:
  
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image", required: false }
      - { label: "Banner Alt", name: "banner_alt", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string", required: true }
      - { label: "Layout", name: "layout", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Is a search page?", name: "is_search", widget: "boolean", default: false, required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image", required: false }
      - { label: "Banner Alt", name: "banner_alt", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string", required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Published Date", name: "date", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Categories", name: "categories", widget: "categories", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: true }

  - name: "timetable"
    label: "Timetable"
    folder: "content/fitness-and-exercise"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title on Front page", name: "front_title", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image", required: false }
      - { label: "Banner Alt", name: "banner_alt", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string", required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Starts At", name: "start_time", widget: "time", required: true }
      - { label: "Ends At", name: "end_time", widget: "time", required: true }
      - label: "Day"
        name: "event_day"
        widget: "select"
        required: true
        options:
        - { label: "Monday", value: "monday" }
        - { label: "Tuesday", value: "tuesday" }
        - { label: "Wednesday", value: "wednesday" }
        - { label: "Thursday", value: "thursday" }
        - { label: "Friday", value: "friday" }
        - { label: "Saturday", value: "saturday" }
        - { label: "Sunday", value: "sunday" }
      - label: "Ability"
        name: "level"
        widget: "select"
        required: true
        options:
        - "Mixed Ability"
        - "Beginners"
        - "Beginners/Intermediate"
        - "Intermediate"
        - "Intermediate/Advanced"
        - "Advanced"
      - { label: "Associate", name: "associate", widget: "string", required: true }
      - { label: "Term", name: "term", widget: "string", required: true }
      - label: "Room"
        name: "room"
        widget: "select"
        required: true
        options:
        - "Studio"
        - "Gym"
        - "Classroom"
      - { label: "Price", name: "price", widget: "string", required: true }

  - name: "therapies"
    label: "Therapies"
    folder: "content/therapies"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image", required: false }
      - { label: "Banner Alt", name: "banner_alt", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string", required: true }
      - { label: "Treatments", name: "treatments", widget: "select", options: ["therapy", "wellbeing", "nutrition", "lifestyle"], required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: true }
      - { label: "Colour", name: "colour", widget: "select", options: ["secondary", "success"], required: true }

  - name: "whats-on"
    label: "Whats on"
    folder: "content/whats-on"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image", required: false }
      - { label: "Banner Alt", name: "banner_alt", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string", required: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Starts At", name: "starts_at", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", required: true }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: true }
      - label: "Featured"
        name: "event_categories"
        widget: "select"
        required: false
        options: 
          - { label: "Featured", value: "featured" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "settings"
    label: "Settings"
    files:

      - label: "Emergency"
        name: "emergency"
        file: "data/emergency.yml"
        description: "Emergency Message"
        fields: 
          - { label: "Enable?", name: "enable", widget: "select", options: ["no", "yes"] }
          - { label: "Message", name: "message", widget: "markdown" }

      - label: "Social"
        name: "social"
        file: "data/social.yml"
        description: "Social"
        fields:
          - { label: "Facebook", name: "facebook", widget: "string" }
          - { label: "Twitter", name: "twitter", widget: "string" }
