backend:
  name: git-gateway
  
media_folder: "content/uploads"
public_folder: "/uploads"
collections:
  
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Published Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }

  - name: "timetable"
    label: "Timetable"
    folder: "content/fitness-and-exercise"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Starts At", name: "start_time", widget: "time" }
      - { label: "Ends At", name: "end_time", widget: "time" }
      - label: "Day"
        name: "event_day"
        widget: "select"
        options:
        - { label: "Monday", value: "monday" }
        - { label: "Tuesday", value: "tuesday" }
        - { label: "Wednesday", value: "wednesday" }
        - { label: "Thursday", value: "thursday" }
        - { label: "Friday", value: "friday" }
        - { label: "Saturday", value: "saturday" }
        - { label: "Sunday", value: "sunday" }
      - label: "Ability"
        name: "level"
        widget: "select"
        options:
        - "Mixed Ability"
        - "Beginners"
        - "Beginners/Intermediate"
        - "Intermediate"
        - "Intermediate/Advanced"
        - "Advanced"
      - { label: "Associate", name: "associate", widget: "string" }
      - { label: "Term", name: "term", widget: "string" }
      - label: "Room"
        name: "room"
        widget: "select"
        options:
        - "Studio"
        - "Gym"
        - "Classroom"
      - { label: "Price", name: "price", widget: "string" }

  - name: "therapies"
    label: "Therapies"
    folder: "content/therapies"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string" }
      - { label: "Categories", name: "categories", widget: "select", options: ["therapy", "wellbeing", "nutrition"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "whats-on"
    label: "Whats on"
    folder: "content/whats-on"
    create: true
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Focus Keyword", name: "yoast_keyword", widget: "string" }
      - { label: "Starts At", name: "start_time", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "settings"
    label: "Settings"
    files:
      
      - label: "Emergency"
        name: "emergency"
        file: "data/emergency.yml"
        description: "Emergency Message"
        fields: 
          - { label: "Enable or Disable", name: "enable", widget: "select", options: ["no", "yes"] }
          - { label: "Message", name: "body", widget: "markdown" }

      - label: "Social"
        name: "social"
        file: "data/social.yml"
        description: "Social"
        fields:
          - { label: "Facebook", name: "facebook", widget: "string" }
          - { label: "Twitter", name: "twitter", widget: "string" }